version: '3.3'

services:
  RatingDB:
    image: mysql:latest
    container_name: ETIAssignment2Rating
    hostname: ETIAssignment2Rating
    networks:
      - myNet
    ports:
      - 80:8080
    environment:
      MYSQL_USER : user2
      MYSQL_PASSWORD : password
    volumes:
      - ./data:/docker-entrypoint initdb.

  CommentDB:
    image: mysql:latest
    container_name: ETIAssignment2Comment
    hostname: ETIAssignment2Comment
    networks:
      - myNet
    ports:
      - 80:8080
    environment:
      MYSQL_USER : user2
      MYSQL_PASSWORD : password
    volumes:
      - ./data:/docker-entrypoint initdb.

  Rating:
    image: mysql:latest
    container_name: RatingContainer
    hostname: RatingContainer
    networks:
      - myNet
    ports:
      - 9072:8080
    volumes:
      - ./data:/docker-entrypoint initdb.
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - RatingDB
  
  Comments:
    image: mysql:latest
    container_name: CommentsContainer
    hostname: CommentsContainer
    networks:
      - myNet
    ports:
      - 9072:8080
    volumes:
      - ./data:/docker-entrypoint initdb.
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - CommentDB
    
  